# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Remote(command_executor='http://localhost:4444/wd/hub', desired_capabilities=DesiredCapabilities.CHROME)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test11(self):
    self.driver.get("http://develop_station.tsdj.nucarf.tech/login")
    self.driver.set_window_size(1282, 760)
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(1) .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(1) .el-input__inner").send_keys("13379190312")
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--text > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".code-item .el-input__inner").click()
    self.driver.find_element(By.CSS_SELECTOR, ".code-item .el-input__inner").send_keys("2514")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-block > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nf-submenu:nth-child(2) > .el-submenu__title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".is-opened .el-menu-item:nth-child(1) > span").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".el-form-item:nth-child(5) .el-range__icon").click()
    self.driver.find_element(By.CSS_SELECTOR, ".today span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".end-date span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--primary:nth-child(1)").click()
    self.driver.find_element(By.ID, "p").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-date-table__row:nth-child(2) > .available:nth-child(5) span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".end-date span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-button--primary:nth-child(1) > span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-button--primary:nth-child(1) > span")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__body-wrapper .el-table__row:nth-child(1) > .el-table_1_column_3 span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-table__body-wrapper .el-table__row:nth-child(1) > .el-table_1_column_3 span")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__body-wrapper .el-table__row:nth-child(1) > .el-table_1_column_2 span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__body-wrapper .el-table__row:nth-child(1) > .el-table_1_column_2 span").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".el-table__body-wrapper .el-table__row:nth-child(1) > .el-table_1_column_2 span")
    actions = ActionChains(self.driver)
    actions.double_click(element).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__body-wrapper .el-table__row:nth-child(1) > .el-table_1_column_2 span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-table__body-wrapper .el-table__row:nth-child(2) > .el-table_1_column_5 span").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tab-\\/ordermanagement > .el-icon-close").click()
    self.driver.find_element(By.CSS_SELECTOR, ".is-opened .el-menu-item:nth-child(2) > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-card:nth-child(1) .el-icon-refresh").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".is-active .el-menu-item:nth-child(1) > span").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".is-active .el-menu-item:nth-child(2)").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.ID, "tab-/ordermanagement").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, "#tab-\\/ordermanagement > .el-icon-close").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tab-\\/reportmanagement > .el-icon-close").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-dropdown-link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-dropdown-menu__item").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-dropdown-link > .name").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-dropdown-menu__item").click()
    self.driver.find_element(By.CSS_SELECTOR, ".nf-submenu:nth-child(3) > .el-submenu__title").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-dropdown-link").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-dropdown-link > .name").click()
    self.driver.find_element(By.CSS_SELECTOR, ".el-dropdown-menu__item").click()
  
